app:
  regions:
    csv: classpath:postcodes.csv
    factors:
      DE_BW: 1.1
      DE_BY: 1.0
      DE_BE: 1.3
      DE_NW: 1.2
      DE_HE: 1.2
      DE_HH: 1.3
      DE_SH: 1.0
      DE_RP: 1.0
      DE_SN: 1.0
      DE_ST: 1.0
      DE_TH: 1.0
      DE_BB: 1.0
      DE_MV: 1.0
      DE_SL: 1.0
server:
  port: ${PORT:8080}
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:h2:file:./data/insurance-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name:
      car-insurance-calculator